{% set name = "dash-mp-components" %}
{% set version = "0.4.47" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dash_mp_components-{{ version }}.tar.gz
  sha256: 68de4ccc543f3ca58ed76fb2c6a6ef797c464bf8f55c93f2c42b75b6ad5bc216

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - dash
    - dash-core-components
    - dash-html-components
    - dash-table

test:
  imports:
    - dash_mp_components
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Dash components for the Materials Project
  license: BSD-3-Clause-LBNL
  license_file: LICENSE
  home: https://github.com/materialsproject/dash-mp-components

extra:
  recipe-maintainers:
    - awvwgk
